# Generated by Django 2.2.28 on 2022-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20220711_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='url_map_store',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
