# Generated by Django 4.0.5 on 2022-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_store_customer_alter_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
