# Generated by Django 3.2.7 on 2022-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_customer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
