# Generated by Django 4.0.5 on 2022-07-06 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0007_store_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='customer',
        ),
        migrations.AddField(
            model_name='store',
            name='customer',
            field=models.ManyToManyField(related_name='store_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
