# Generated by Django 4.0.5 on 2022-07-06 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0008_remove_store_customer_store_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, related_name='store_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
