# Generated by Django 3.2.7 on 2022-10-02 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_alter_store_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='message2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phone', models.CharField(max_length=11)),
                ('to_phone', models.CharField(max_length=11)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Success'), (1, 'Failed')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.store')),
            ],
        ),
    ]
