# Generated by Django 3.2.7 on 2022-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20221002_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
