# Generated by Django 3.2.7 on 2022-10-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_messagelog_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='from_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Success'), (1, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='to_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
